"use client";

import { ComponentType } from "react";
import {
  Activity,
  Baby,
  Battery,
  Bath,
  Bike,
  Book,
  BookOpen,
  Box,
  Building,
  Bus,
  Car,
  ChefHat,
  Coffee,
  CreditCard,
  Dog,
  DoorOpen,
  Droplet,
  Droplets,
  Dumbbell,
  Eye,
  Fan,
  Fence,
  Fish,
  Flame,
  Flame as FireIcon,
  Flower,
  Flower2,
  Footprints,
  ForkKnife,
  Gamepad2,
  GraduationCap,
  Hammer,
  Heart,
  Hospital,
  Home,
  Key,
  Lamp,
  Layers,
  Leaf,
  Lightbulb,
  Lock,
  MapPin,
  Microwave,
  Monitor,
  Moon,
  MoreHorizontal,
  Mountain,
  Music,
  Package,
  ParkingSquare,
  PartyPopper,
  Phone,
  PhoneCall,
  Plane,
  Plug,
  Recycle,
  Refrigerator,
  Route,
  Ruler,
  Settings,
  Shield,
  ShieldCheck,
  Ship,
  ShoppingBag,
  Snowflake,
  Sofa,
  Sparkles,
  Sprout,
  Square,
  Star,
  Sun,
  Target,
  Tent,
  Thermometer,
  TreeDeciduous,
  TreePine,
  Trophy,
  Tv,
  Umbrella,
  User,
  Users,
  UtensilsCrossed,
  Warehouse,
  Waves,
  Wifi,
  Wind,
  Wrench,
  Zap,
} from "lucide-react";

export type DetailIcon = ComponentType<{ size?: number; className?: string }>;

const amenityIconMap: Record<string, DetailIcon> = {
  gym: Dumbbell,
  pool: Waves,
  sauna: Sparkles,
  party_room: PartyPopper,
  playground: Baby,
  gourmet_area: ChefHat,
  tennis_court: Trophy,
  barbecue_area: Flame,
  multipurpose_court: Trophy,
};

export function getAmenityIcon(amenity: string): DetailIcon {
  return amenityIconMap[amenity] || Building;
}

export type FeatureInfo = {
  label: string;
  icon: DetailIcon;
};

const featureMap: Record<string, FeatureInfo> = {
  administration: { label: "Administração", icon: Building },
  adult_pool: { label: "Piscina Adulto", icon: Waves },
  alarm_system: { label: "Sistema de Alarme", icon: Shield },
  aluminium_window: { label: "Janelas de Alumínio", icon: Eye },
  american_kitchen: { label: "Cozinha Americana", icon: UtensilsCrossed },
  aquarium: { label: "Aquário", icon: Fish },
  armored_security_cabin: { label: "Cabine de Segurança Blindada", icon: ShieldCheck },
  artesian_well: { label: "Poço Artesiano", icon: Droplet },
  background_house: { label: "Casa de Fundos", icon: Home },
  backyard: { label: "Quintal", icon: TreePine },
  balcony: { label: "Varanda", icon: Umbrella },
  band_practice_room: { label: "Sala de Ensaio", icon: Music },
  bar: { label: "Bar", icon: Coffee },
  barbecue_area: { label: "Área de Churrasqueira", icon: Flame },
  barbecue_balcony: { label: "Varanda Gourmet", icon: ChefHat },
  barbecue_grill: { label: "Grelha", icon: Flame },
  barn: { label: "Celeiro", icon: Warehouse },
  basketball_court: { label: "Quadra de Basquete", icon: Target },
  bathroom_cabinets: { label: "Armários no Banheiro", icon: Package },
  bathtub: { label: "Banheira", icon: Bath },
  bbq: { label: "Churrasqueira", icon: Flame },
  beauty_center: { label: "Centro de Beleza", icon: Sparkles },
  beauty_room: { label: "Sala de Beleza", icon: Sparkles },
  beauty_salon: { label: "Salão de Beleza", icon: Sparkles },
  bedroom_wardrobe: { label: "Roupeiro no Quarto", icon: Package },
  bicycles_place: { label: "Bicicletário", icon: Bike },
  blindex_box: { label: "Caixa Blindex", icon: Shield },
  builtin_wardrobe: { label: "Roupeiro Embutido", icon: Package },
  burn_cement: { label: "Cimento Queimado", icon: Hammer },
  cable_television: { label: "TV a Cabo", icon: Tv },
  caretaker: { label: "Zelador", icon: User },
  caretaker_house: { label: "Casa do Zelador", icon: Home },
  carpet: { label: "Carpete", icon: Sofa },
  children_care: { label: "Berçário", icon: Baby },
  children_pool: { label: "Piscina Infantil", icon: Waves },
  childrens_pool: { label: "Piscina para Crianças", icon: Waves },
  climbing_wall: { label: "Parede de Escalada", icon: Mountain },
  close_to_hospitals: { label: "Próximo a Hospitais", icon: Hospital },
  close_to_main_roads: { label: "Próximo a Vias Principais", icon: Route },
  close_to_public_transport: { label: "Próximo ao Transporte Público", icon: Bus },
  close_to_schools: { label: "Próximo a Escolas", icon: GraduationCap },
  close_to_shopping_centers: { label: "Próximo a Shopping Centers", icon: ShoppingBag },
  closet: { label: "Armário", icon: Package },
  closet_room: { label: "Quarto de Depósito", icon: Package },
  coffee_shop: { label: "Cafeteria", icon: Coffee },
  cold_floor: { label: "Piso Frio", icon: Snowflake },
  concierge_24h: { label: "Portaria 24h", icon: ShieldCheck },
  controlled_access: { label: "Acesso Controlado", icon: Lock },
  convention_hall: { label: "Salão de Convenções", icon: Building },
  cooker: { label: "Fogão", icon: Flame },
  cooling: { label: "Ar Condicionado", icon: Snowflake },
  copa: { label: "Copa", icon: UtensilsCrossed },
  corner_property: { label: "Imóvel de Esquina", icon: Home },
  corral: { label: "Curral", icon: Fence },
  coverage: { label: "Cobertura", icon: Umbrella },
  covered_parking: { label: "Estacionamento Coberto", icon: ParkingSquare },
  covered_pool: { label: "Piscina Coberta", icon: Waves },
  coworking: { label: "Coworking", icon: Monitor },
  coworking_room: { label: "Sala de Coworking", icon: Monitor },
  deck: { label: "Deck", icon: Umbrella },
  deck_area: { label: "Área de Deck", icon: Umbrella },
  digital_locker: { label: "Cofre Digital", icon: Lock },
  dinner_room: { label: "Sala de Jantar", icon: UtensilsCrossed },
  disabled_access: { label: "Acesso para Deficientes", icon: Users },
  dividers: { label: "Divisórias", icon: Layers },
  dog_kennel: { label: "Canil", icon: Dog },
  dress_room2: { label: "Vestiário", icon: Package },
  drywall: { label: "Drywall", icon: Hammer },
  eco_condominium: { label: "Condomínio Ecológico", icon: Leaf },
  eco_garbage_collector: { label: "Coleta Seletiva", icon: Recycle },
  edicule: { label: "Edícula", icon: Home },
  electric_charger: { label: "Carregador Elétrico", icon: Plug },
  electric_fence: { label: "Cerca Elétrica", icon: Fence },
  electronic_gate: { label: "Portão Eletrônico", icon: Lock },
  elevator: { label: "Elevador", icon: Layers },
  employee_dependency: { label: "Dependência de Empregada", icon: Home },
  entrance_hall: { label: "Hall de Entrada", icon: DoorOpen },
  exterior_view: { label: "Vista Externa", icon: Eye },
  fence: { label: "Cerca", icon: Fence },
  fenced_yard: { label: "Quintal Cercado", icon: Fence },
  fireplace: { label: "Lareira", icon: FireIcon },
  fitness_room: { label: "Sala de Fitness", icon: Dumbbell },
  football_field: { label: "Campo de Futebol", icon: Activity },
  freezer: { label: "Freezer", icon: Refrigerator },
  fruit_trees: { label: "Árvores Frutíferas", icon: TreePine },
  full_floor: { label: "Andar Inteiro", icon: Layers },
  fully_wired: { label: "Totalmente Fiação", icon: Zap },
  furnished: { label: "Mobiliado", icon: Sofa },
  game_room: { label: "Sala de Jogos", icon: Gamepad2 },
  game_room_kids: { label: "Sala de Jogos Infantil", icon: Gamepad2 },
  game_room_teen: { label: "Sala de Jogos para Adolescentes", icon: Gamepad2 },
  garden: { label: "Jardim", icon: Flower2 },
  garden_area: { label: "Área de Jardim", icon: Flower2 },
  gas_shower: { label: "Chuveiro a Gás", icon: Droplets },
  geminada: { label: "Geminada", icon: Home },
  generator: { label: "Gerador", icon: Battery },
  glass_wall: { label: "Parede de Vidro", icon: Eye },
  golf_course: { label: "Campo de Golfe", icon: Target },
  golf_field: { label: "Campo de Golfe", icon: Target },
  gourmet_area: { label: "Área Gourmet", icon: ChefHat },
  gourmet_balcony: { label: "Varanda Gourmet", icon: ChefHat },
  gourmet_kitchen: { label: "Cozinha Gourmet", icon: ChefHat },
  gravel: { label: "Cascalho", icon: Sprout },
  green_area: { label: "Área Verde", icon: Leaf },
  green_space_park: { label: "Parque de Área Verde", icon: TreePine },
  guest_parking: { label: "Estacionamento para Visitantes", icon: ParkingSquare },
  gym: { label: "Academia", icon: Dumbbell },
  half_floor: { label: "Meio Andar", icon: Layers },
  hammock_garden: { label: "Jardim de Redes", icon: Tent },
  headquarters: { label: "Sede", icon: Building },
  heated_pool: { label: "Piscina Aquecida", icon: Waves },
  heating: { label: "Aquecimento", icon: Thermometer },
  helipad: { label: "Heliponto", icon: Plane },
  high_ceiling_height: { label: "Pé Direito Alto", icon: Layers },
  home_office: { label: "Home Office", icon: Monitor },
  hot_tub: { label: "Ofurô", icon: Waves },
  indoor_soccer: { label: "Futebol de Salão", icon: Activity },
  integrated_environments: { label: "Ambientes Integrados", icon: Home },
  intercom: { label: "Interfone", icon: PhoneCall },
  internet_connection: { label: "Conexão de Internet", icon: Wifi },
  jogging_track: { label: "Pista de Corrida", icon: Activity },
  kids_area: { label: "Área Infantil", icon: Baby },
  kitchen: { label: "Cozinha", icon: UtensilsCrossed },
  kitchen_cabinets: { label: "Armários de Cozinha", icon: Package },
  lake: { label: "Lago", icon: Waves },
  lake_view: { label: "Vista para o Lago", icon: Eye },
  laminated_floor: { label: "Piso Laminado", icon: Layers },
  land: { label: "Terreno", icon: Sprout },
  large_kitchen: { label: "Cozinha Grande", icon: UtensilsCrossed },
  large_room: { label: "Sala Grande", icon: Home },
  large_window: { label: "Janela Grande", icon: Eye },
  laundry: { label: "Lavanderia", icon: Waves },
  laundry_room: { label: "Área de Serviço", icon: Waves },
  lavabo: { label: "Lavabo", icon: Bath },
  lawn: { label: "Gramado", icon: Sprout },
  library: { label: "Biblioteca", icon: Book },
  library_room: { label: "Sala de Biblioteca", icon: BookOpen },
  lunch_room: { label: "Sala de Almoço", icon: UtensilsCrossed },
  maids_quarters: { label: "Quarto de Empregada", icon: Home },
  marina: { label: "Marina", icon: Ship },
  massage_room: { label: "Sala de Massagem", icon: Heart },
  media_room: { label: "Sala de Mídia", icon: Monitor },
  meeting_room: { label: "Sala de Reuniões", icon: Users },
  mezzanine: { label: "Mezanino", icon: Layers },
  mountain_view: { label: "Vista para Montanha", icon: Mountain },
  natural_ventilation: { label: "Ventilação Natural", icon: Wind },
  near_shopping_center: { label: "Próximo a Shopping Center", icon: ShoppingBag },
  number_of_stories: { label: "Andares", icon: Layers },
  ocean_view: { label: "Vista para o Oceano", icon: Waves },
  orchid_garden: { label: "Orquidário", icon: Flower },
  orchid_garden_area: { label: "Área de Orquidário", icon: Flower },
  orchid_place: { label: "Orquidário", icon: Flower },
  others: { label: "Outros", icon: MoreHorizontal },
  panoramic_view: { label: "Vista Panorâmica", icon: Eye },
  pantry: { label: "Despensa", icon: Package },
  parking_garage: { label: "Garagem", icon: Car },
  party_gourmet_area: { label: "Área Gourmet para Festas", icon: PartyPopper },
  party_room: { label: "Salão de Festas", icon: PartyPopper },
  pasture: { label: "Pastagem", icon: Sprout },
  patrol: { label: "Ronda", icon: ShieldCheck },
  paved_street: { label: "Rua Pavimentada", icon: Route },
  pay_per_use_services: { label: "Serviços Pay-per-Use", icon: CreditCard },
  pet_space: { label: "Espaço para Pets", icon: Dog },
  pets_allowed: { label: "Permite Pets", icon: Footprints },
  pizza_oven: { label: "Forno de Pizza", icon: Flame },
  planned_furniture: { label: "Móveis Planejados", icon: Sofa },
  platibanda: { label: "Platibanda", icon: Layers },
  playground: { label: "Playground", icon: Baby },
  playground_sand_pit: { label: "Playground com Areia", icon: Baby },
  pomar: { label: "Pomar", icon: TreePine },
  pool: { label: "Piscina", icon: Waves },
  pool_bar: { label: "Bar da Piscina", icon: Coffee },
  porcelain: { label: "Porcelanato", icon: Layers },
  private_pool: { label: "Piscina Privativa", icon: Waves },
  raised_floor: { label: "Piso Elevado", icon: Layers },
  reception_room: { label: "Sala de Recepção", icon: DoorOpen },
  recreation_area: { label: "Área de Recreação", icon: Activity },
  redario: { label: "Redário", icon: Tent },
  reflective_pool: { label: "Espelho d'Água", icon: Waves },
  restaurant: { label: "Restaurante", icon: UtensilsCrossed },
  restaurant_area: { label: "Área de Restaurante", icon: UtensilsCrossed },
  reversible_room: { label: "Quarto Reversível", icon: Home },
  river: { label: "Rio", icon: Waves },
  sanca: { label: "Sanca", icon: Layers },
  sand_pit: { label: "Caixa de Areia", icon: Baby },
  sauna: { label: "Sauna", icon: Thermometer },
  sauna_dry: { label: "Sauna Seca", icon: Thermometer },
  sauna_wet: { label: "Sauna Úmida", icon: Thermometer },
  security_camera: { label: "Câmera de Segurança", icon: Eye },
  security_guard_on_duty: { label: "Segurança em Plantão", icon: ShieldCheck },
  security_guardhouse: { label: "Guarita de Segurança", icon: Shield },
  security_patrol: { label: "Ronda de Segurança", icon: ShieldCheck },
  semi_olympic_pool: { label: "Piscina Semi Olímpica", icon: Waves },
  service_bathroom: { label: "Banheiro de Serviço", icon: Bath },
  service_entrance: { label: "Entrada de Serviço", icon: DoorOpen },
  service_room: { label: "Quarto de Serviço", icon: Home },
  side_entrance: { label: "Entrada Lateral", icon: DoorOpen },
  skate_lane: { label: "Pista de Skate", icon: Activity },
  slab: { label: "Laje", icon: Layers },
  small_room: { label: "Quarto Pequeno", icon: Home },
  smart_apartment: { label: "Apartamento Inteligente", icon: Zap },
  smart_condominium: { label: "Condomínio Inteligente", icon: Zap },
  solar_energy: { label: "Energia Solar", icon: Sun },
  solarium: { label: "Solário", icon: Sun },
  soundproofing: { label: "Isolamento Acústico", icon: Shield },
  spa: { label: "SPA", icon: Heart },
  spa_area: { label: "Área SPA", icon: Heart },
  sports_court: { label: "Quadra Esportiva", icon: Trophy },
  square: { label: "Praça", icon: TreePine },
  square_plaza: { label: "Praça", icon: TreePine },
  squash: { label: "Squash", icon: Activity },
  squash_court: { label: "Quadra de Squash", icon: Activity },
  stair: { label: "Escada", icon: Layers },
  storage_warehouse: { label: "Depósito", icon: Warehouse },
  stores: { label: "Lojas", icon: ShoppingBag },
  stores_at_condo: { label: "Lojas no Condomínio", icon: ShoppingBag },
  teen_space: { label: "Espaço para Adolescentes", icon: Users },
  tennis_court: { label: "Quadra de Tênis", icon: Trophy },
  tennis_wall: { label: "Parede de Tênis", icon: Trophy },
  thermal_insulation: { label: "Isolamento Térmico", icon: Thermometer },
  toys_place: { label: "Espaço para Brinquedos", icon: Baby },
  tree_climbing: { label: "Escalada de Árvore", icon: TreePine },
  tv_security: { label: "TV de Segurança", icon: Tv },
  utilities: { label: "Utilitários", icon: Wrench },
  utilities_room: { label: "Quarto de Utilitários", icon: Wrench },
  valet_parking: { label: "Estacionamento com Manobrista", icon: ParkingSquare },
  vegetable_garden: { label: "Horta", icon: Sprout },
  vinyl_floor: { label: "Piso Vinílico", icon: Layers },
  wall_balcony: { label: "Sacada", icon: Umbrella },
  walls_grids: { label: "Grades nas Paredes", icon: Fence },
  warehouse: { label: "Armazém", icon: Warehouse },
  water_tank: { label: "Caixa d'Água", icon: Droplet },
  well: { label: "Poço", icon: Droplet },
  whirlpool: { label: "Hidromassagem", icon: Droplets },
  wood_floor: { label: "Piso de Madeira", icon: TreePine },
  zen_garden: { label: "Jardim Zen", icon: Flower2 },
  zen_space: { label: "Espaço Zen", icon: Flower2 },
};

export function getFeatureInfo(key: string): FeatureInfo {
  return featureMap[key] || { label: key.replace(/_/g, " "), icon: Building };
}


